### ISSUE TITLE
Include general convention on Wilson Coefficients and operators

### ISSUE THREAD

**Issue by peterstangl** [flav-io/flav-io.github.io#4]
It might be useful to include in https://flav-io.github.io/docs/operators.html the general convention on Wilson Coefficients and operators, namely the first paragraph in https://arxiv.org/pdf/1712.05298.pdf on page 5.
Alternatively, it could also be convenient to add these conventions to the beginning of the PDF file that lists all operators.

**Comment by DavidMStraub** [comment]
Good idea. I added the equation to all basis PDFs.
