### ISSUE TITLE
Broken link on FastFit page

### ISSUE THREAD

**Issue by MJKirk** [flav-io/flav-io.github.io#7]
The link to the API docs on the FastFit page (https://flav-io.github.io/docs/fastfit.html) is broken.
Fixed by https://github.com/MJKirk/flav-io.github.io/commit/8631531e18a295742595f1ea54ab57fba6c7644b.

**Comment by DavidMStraub** [comment]
Thanks! By the way, if you're using `FastFit`, you might want to have a look at `flavio.statistics.likelihood.FastLikelihood`, which is a more recent reimplementation of a very similar use case, and is more actively developed.

**Comment by DavidMStraub** [comment]
(I should document that...)
